echo ""
echo "Debes configurar LDIF (ficheros llave de LDAP de nominados Data Interchange Format)"
echo "Tecleamos para acceder en el directorio de configuracion"
echo ""
echo "$ cd /etc/openldap/slapd.d/cn=config"
echo ""
echo "Definimos el nombre del servidor modificando las raices 'dc' y 'dc'"
echo "Tambien definimos el usuario y su nivel de acceso 'cn'"
echo "Para acabar definimos una password para el usuario manager añadiendo la clausula olcRootPW: <<HASH>>"
echo ""
echo "Generamos una password, copiamos para llevarla al archivo de configuración"
echo ""
echo "$ slappasswd"
echo ""
echo "$ nano olcDatabase={2}hdb.ldif"
echo "-----------------------------------------------------"
echo "# AUTO-GENERATED FILE - DO NOT EDIT!! Use ldapmodify."
echo "# CRC32 b858cbbd"
echo "dn: olcDatabase={2}hdb"
echo "objectClass: olcDatabaseConfig"
echo "objectClass: olcHdbConfig"
echo "olcDatabase: {2}hdb"
echo "olcDbDirectory: /var/lib/ldap"
echo "olcSuffix: dc=asmt03,dc=org                        <<------ dc=asmt03,dc=org"
echo "olcRootDN: cn=Manager,dc=asmt03,dc=org             <<------ dc=asmt03,dc=org"
echo "olcRootPW: {SSHA}9Dc3Fh9DTBvBmxNPZHYjrXfbU7HMf8lq  <<------ Incluimos esta linea y una password"
echo "olcDbIndex: objectClass eq,pres"
echo "olcDbIndex: ou,cn,mail,surname,givenname eq,pres,sub"
echo "structuralObjectClass: olcHdbConfig"
echo "entryUUID: bbea32e2-bae3-1037-97c9-9dd5e23362f7"
echo "creatorsName: cn=config"
echo "createTimestamp: 20180313082446Z"
echo "entryCSN: 20180313082446.711639Z#000000#000#000000"
echo "modifiersName: cn=config"
echo "modifyTimestamp: 20180313082446Z"
echo "----------------------------------------------------"
echo ""
echo "Ahora configuramos tambien el siguiente archivo dejandolo como esta abajo"
echo ""
echo "$ nano olcDatabase={1}monitor.ldif"
echo ""
echo "-----------------------------------------------------------------------------"
echo "# AUTO-GENERATED FILE - DO NOT EDIT!! Use ldapmodify."
echo "# CRC32 5124ef22"
echo "dn: olcDatabase={1}monitor"
echo "objectClass: olcDatabaseConfig"
echo "olcDatabase: {1}monitor"
echo "olcAccess: {0}to * by dn.base=\"gidNumber=0+uidNumber=0,cn=peercred,cn=extern"
echo " al,cn=auth\" read by dn.base=\"cn=Manager,dc=asmt03,dc=org\" read by * none         <<------ dc=asmt03,dc=org"
echo "structuralObjectClass: olcDatabaseConfig"
echo "entryUUID: bbea27fc-bae3-1037-97c8-9dd5e23362f7"
echo "creatorsName: cn=config"
echo "createTimestamp: 20180313082446Z"
echo "entryCSN: 20180313082446.711360Z#000000#000#000000"
echo "modifiersName: cn=config"
echo "modifyTimestamp: 20180313082446Z"
echo "-----------------------------------------------------------------------------"
echo ""
echo "[END]"
